apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-db
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  selector:
    app: account-api
  ports:
    - name: http
      port: 8080
      nodePort: 30000
  type: NodePort

