apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: LoadBalancer
  selector:
    app: postgres-db
  ports:
    - port: 5432
#      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  type: LoadBalancer
  selector:
    app: account-api
  ports:
    - name: http
      port: 8080
#      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    app: zookeeper-svc
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 2181
      nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    name: kafka-svc
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 30092
      nodePort: 30092


