version: '3.8'
services:
  postgres-db:
    image: postgres:13.0-alpine
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'

  customer:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-customer-k8s:latest
    container_name: spring-boot-customer-k8s
    expose:
      - "8080/tcp"
      - "5005/tcp"
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - 'WAIT_HOSTS=postgres:5432'
      - 'POSTGRES_HOST=postgres-db'
    depends_on:
      - postgres-db

